In [37]:
import numpy as np

## DataTypes & Attributes

In [38]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [39]:
type(a1)

numpy.ndarray

In [40]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a1.shape

(3,)

In [44]:
a2.shape

(2, 3)

In [45]:
a3.shape

(2, 3, 3)

In [46]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [47]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [48]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [49]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [50]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating numpy arrays

In [51]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [52]:
sample_array.dtype

dtype('int64')

In [53]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
ones.dtype

dtype('float64')

In [55]:
type(ones)

numpy.ndarray

In [56]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [59]:
random_array = np.random.randint(0,10,size=(3, 5))
random_array

array([[1, 5, 8, 0, 9],
       [6, 7, 9, 7, 2],
       [5, 2, 6, 4, 2]])

In [60]:
range_array.size

5

In [61]:
random_array.shape

(3, 5)

In [62]:
random_array_2 = np.random.random(size=(3, 5))
random_array_2

array([[0.03466477, 0.98679262, 0.07541695, 0.71909374, 0.84601544],
       [0.35061931, 0.23777206, 0.02397824, 0.88598427, 0.47729025],
       [0.78705255, 0.34468669, 0.63747196, 0.21351755, 0.60035303]])

In [63]:
random_array.shape

(3, 5)

In [ ]:
randomed_array_3 = np.random.rand(5, 3)
randomed_array_3

array([[0.715326  , 0.79154796, 0.47574305],
       [0.25651203, 0.47003513, 0.21643079],
       [0.05376933, 0.78515412, 0.94301753],
       [0.8339605 , 0.24338305, 0.36374379],
       [0.61300553, 0.81853739, 0.02514124]])

In [70]:
# Pseudo-random number generation
np.random.seed(seed=42)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])