In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating numpy arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((1, 3))
ones

array([[1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10,size=(3, 5))
random_array

array([[9, 7, 8, 6, 8],
       [8, 2, 6, 3, 1],
       [0, 9, 0, 9, 5]])

In [23]:
range_array.size

5

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random(size=(3, 5))
random_array_2

array([[0.52369166, 0.2635054 , 0.03588445, 0.17703139, 0.03193179],
       [0.64883429, 0.50965961, 0.11273085, 0.83660909, 0.70514329],
       [0.48973641, 0.43396966, 0.53661458, 0.81321728, 0.61665513]])

In [26]:
random_array.shape

(3, 5)

In [27]:
randomed_array_3 = np.random.rand(5, 3)
randomed_array_3

array([[0.46514598, 0.67910189, 0.27132597],
       [0.89044359, 0.0181334 , 0.37792493],
       [0.09630798, 0.39357117, 0.24598766],
       [0.99976506, 0.8735084 , 0.66261864],
       [0.38068747, 0.11224406, 0.0018039 ]])

In [28]:
# Pseudo-random number generation
np.random.seed(seed=42)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [29]:
rng = np.random.default_rng(seed=7)
random_array_5 = rng.random(size=(5, 3))
random_array_5

array([[0.62509547, 0.8972138 , 0.77568569],
       [0.22520719, 0.30016628, 0.87355345],
       [0.0052653 , 0.82122842, 0.79706943],
       [0.46793495, 0.30303243, 0.27842561],
       [0.25486959, 0.44507631, 0.50454826]])

###  3. Viewing arrays and matrices

In [30]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a3[:2, :2, :2]  # Slicing the first two elements in the first two dimensions

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [33]:
a4 = rng.integers(0, 10, size=(2, 3, 4, 5))
a4

array([[[[5, 5, 5, 9, 8],
         [7, 7, 6, 3, 9],
         [4, 2, 8, 1, 8],
         [6, 1, 0, 4, 0]],

        [[1, 5, 9, 4, 8],
         [9, 8, 6, 4, 5],
         [2, 4, 3, 2, 9],
         [0, 0, 1, 9, 6]],

        [[8, 2, 7, 3, 4],
         [0, 6, 8, 6, 1],
         [5, 2, 9, 8, 1],
         [5, 9, 8, 7, 6]]],


       [[[0, 7, 4, 0, 2],
         [5, 7, 5, 6, 8],
         [6, 3, 6, 5, 1],
         [0, 6, 3, 5, 3]],

        [[2, 1, 3, 8, 4],
         [3, 5, 9, 3, 5],
         [4, 6, 4, 6, 5],
         [6, 9, 1, 5, 4]],

        [[3, 2, 0, 4, 8],
         [0, 4, 9, 9, 2],
         [0, 6, 0, 3, 4],
         [8, 0, 6, 5, 1]]]])

In [34]:
a4.shape, a4.ndim, a4.size

((2, 3, 4, 5), 4, 120)

In [35]:
a4[:, :, :, :4]

array([[[[5, 5, 5, 9],
         [7, 7, 6, 3],
         [4, 2, 8, 1],
         [6, 1, 0, 4]],

        [[1, 5, 9, 4],
         [9, 8, 6, 4],
         [2, 4, 3, 2],
         [0, 0, 1, 9]],

        [[8, 2, 7, 3],
         [0, 6, 8, 6],
         [5, 2, 9, 8],
         [5, 9, 8, 7]]],


       [[[0, 7, 4, 0],
         [5, 7, 5, 6],
         [6, 3, 6, 5],
         [0, 6, 3, 5]],

        [[2, 1, 3, 8],
         [3, 5, 9, 3],
         [4, 6, 4, 6],
         [6, 9, 1, 5]],

        [[3, 2, 0, 4],
         [0, 4, 9, 9],
         [0, 6, 0, 3],
         [8, 0, 6, 5]]]])

### 4. Manipulating & comparing arrays

#### Arithmetic

In [36]:
a1

array([1, 2, 3])

In [37]:
ones

array([[1., 1., 1.]])

In [38]:
a1 + ones  # Broadcasting: adding a 1D array to a 2D array

array([[2., 3., 4.]])

In [39]:
a1 - ones  # Broadcasting: subtracting a 1D array from a 2D array

array([[0., 1., 2.]])

In [40]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [41]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [43]:
a1 / ones  # Broadcasting: dividing a 1D array by a 2D array

array([[1., 2., 3.]])

In [44]:
a1 // ones  # Integer division with broadcasting

array([[1., 2., 3.]])

In [ ]:
a2 ** 2 # Element-wise squaring of a 2D array

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [48]:
np.square(a2) # Element-wise squaring using NumPy's square function

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [49]:
np.add(a1, ones)  # Adding a 1D array to a 2D array using NumPy's add function

array([[2., 3., 4.]])

In [50]:
a1 % 2

array([1, 0, 1])

In [51]:
np.exp(a1)  # Element-wise exponentiation

array([ 2.71828183,  7.3890561 , 20.08553692])

In [52]:
np.log(a1)  # Element-wise logarithm

array([0.        , 0.69314718, 1.09861229])

### Aggregation